n1 = int(input('Me diga o valor do primeiro inteiro: '))
n2 = int(input('Me diga o valor do segundo inteiro: '))
n3 = float(input('Me diga o valor de um float: '))
a = (n1 * 2) * (n2 / 2)
b = (n1 * 3) + (n3 * 3)
c = (n3**3)
print("A resposta de a: ",a)
print("A resposta de b: ",b)
print("A resposta de c: ",c)
